global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "agent-engine-api"
    metrics_path: "/metrics/"
    scheme: "http"
    static_configs:
      - targets: ["localhost:7860"]

remote_write:
  - url: https://prometheus-prod-43-prod-ap-south-1.grafana.net/api/prom/push
    basic_auth:
      username: 3263324
      password: ${GRAFANA_API_KEY}