[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

[program:api]
command=uvicorn app.main:app --host 0.0.0.0 --port 7860
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:celery]
command=celery -A app.workers.celery_worker.celery_app worker --loglevel=info --concurrency=2
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:prometheus]
command=bash -c "sed -i \"s|\\\${GRAFANA_API_KEY}|\$GRAFANA_API_KEY|g\" /code/prometheus.yml && prometheus --config.file=/code/prometheus.yml --storage.tsdb.path=/code/prometheus_data"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
